CREATE TABLESPACE tsb_data
DATAFILE '/opt/oracle/oradata/ORCLCDB/PDB_BASKETBALLP_19C/tsb_data01.dbf'
SIZE 200M AUTOEXTEND ON NEXT 50M MAXSIZE 500M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE tsb_idx
DATAFILE '/opt/oracle/oradata/ORCLCDB/PDB_BASKETBALLP_19C/tsb_idx01.dbf'
SIZE 100M AUTOEXTEND ON NEXT 25M MAXSIZE 500M;


CREATE TEMPORARY TABLESPACE tsb_temp
TEMPFILE '/opt/oracle/oradata/ORCLCDB/PDB_BASKETBALLP_19C/tsb_temp01.dbf'
SIZE 50M AUTOEXTEND ON NEXT 25M;

