CREATE USER admin_bf IDENTIFIED BY Sales2025
DEFAULT TABLESPACE tsb_data
TEMPORARY TABLESPACE tsb_temp
QUOTA UNLIMITED ON tsb_data
QUOTA UNLIMITED ON tsb_idx
PROFILE DEFAULT
ACCOUNT UNLOCK;


GRANT CREATE SESSION TO admin_bf;

GRANT CREATE TABLE,
      CREATE VIEW,
      CREATE PROCEDURE,
      CREATE SEQUENCE,
      CREATE TRIGGER
TO admin_bf;
